"""
main.py

Project entry point. Automatically selects the best-performing trained
model across all four algorithms (by reading results/hyperparameter_tables/,
generated by results/analysis.py) and runs it for one or more episodes,
optionally with a live Pygame render -- the same underlying rendering path
as play.py, which this module reuses.

If results/hyperparameter_tables/ has not been generated yet (i.e. no
training has been run), falls back to an explicit --algo/--model pair.

Usage:
    python main.py                                   # auto-select best model
    python main.py --algo ppo --model models/ppo/ppo_07.zip --episodes 3
    python main.py --no-render
"""

from __future__ import annotations

import argparse
import glob
import os

import pandas as pd

from environment.custom_env import WasteSegregationEnv
from play import play_episode
from training.utils import load_agent

MODEL_EXTENSION = {"dqn": "zip", "a2c": "zip", "ppo": "zip", "reinforce": "pt"}


class _RandomAgent:
    """Fallback agent for a fresh clone with no trained models. Exposes the
    same `.predict(obs, deterministic=...)` signature as every trained agent."""

    def __init__(self, action_space) -> None:
        self._action_space = action_space

    def predict(self, obs, deterministic: bool = True):
        return self._action_space.sample(), None


def find_best_model(tables_dir: str = "results/hyperparameter_tables",
                     models_root: str = "models") -> tuple[str, str] | None:
    """Scan every algorithm's hyperparameter table and return (algo, model_path)
    for the run with the highest mean_reward_last_10pct, or None if no
    tables/logs are available yet.
    """
    best = None  # (score, algo, run_id)
    for table_path in glob.glob(os.path.join(tables_dir, "*_hyperparameters.csv")):
        algo = os.path.basename(table_path).replace("_hyperparameters.csv", "")
        df = pd.read_csv(table_path)
        df = df.dropna(subset=["mean_reward_last_10pct"])
        if df.empty:
            continue
        row = df.loc[df["mean_reward_last_10pct"].idxmax()]
        score = float(row["mean_reward_last_10pct"])
        if best is None or score > best[0]:
            best = (score, algo, row["run_id"])

    if best is None:
        return None

    _, algo, run_id = best
    ext = MODEL_EXTENSION[algo]
    model_path = os.path.join(models_root, algo, f"{run_id}.{ext}")
    if not os.path.exists(model_path):
        return None
    return algo, model_path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run the best trained WasteSegregationEnv agent (or a specified one)."
    )
    parser.add_argument("--algo", choices=["dqn", "reinforce", "a2c", "ppo"], default=None)
    parser.add_argument("--model", default=None, help="Path to a specific model file.")
    parser.add_argument("--episodes", type=int, default=1)
    parser.add_argument("--no-render", action="store_true")
    parser.add_argument("--seed", type=int, default=None)
    args = parser.parse_args()

    algo, model_path = None, None
    if args.algo and args.model:
        algo, model_path = args.algo, args.model
    else:
        found = find_best_model()
        if found is not None:
            algo, model_path = found
            print(f"Auto-selected best model: algo={algo}, path={model_path}")

    render_mode = None if args.no_render else "human"
    env = WasteSegregationEnv(render_mode=render_mode, seed=args.seed)

    if model_path is None:
        # Fresh clone with no trained models yet: fall back to a random agent
        # so `uv run main.py` still runs end to end and shows the environment.
        # (Train an algorithm + run `python -m results.analysis` to unlock the
        # real best-model auto-selection.)
        print(
            "No trained models found -- running a RANDOM-action demo so you can "
            "see the environment. Train an algorithm (training/*.py or the Colab "
            "notebooks) and run `python -m results.analysis`, then re-run this to "
            "watch the best trained agent."
        )
        agent = _RandomAgent(env.action_space)
    else:
        agent = load_agent(
            algo, model_path,
            obs_dim=env.observation_space.shape[0], n_actions=env.action_space.n,
        )

    rewards = []
    for ep in range(args.episodes):
        print(f"\n=== Episode {ep + 1}/{args.episodes} ===")
        rewards.append(play_episode(env, agent, verbose=True))

    env.close()
    if len(rewards) > 1:
        print(f"\nMean reward over {len(rewards)} episodes: {sum(rewards) / len(rewards):.2f}")


if __name__ == "__main__":
    main()
